//--------[ PERK INCLUDE ]------------[ ID ]--------

#include "rtd/godmode.sp"			//	0
#include "rtd/toxic.sp"				//	1
#include "rtd/luckysandvich.sp"		//	2
#include "rtd/increasedspeed.sp"	//	3
#include "rtd/noclip.sp"			//	4
#include "rtd/lowgravity.sp"		//	5
#include "rtd/fullubercharge.sp"	//	6
#include "rtd/invisibility.sp"		//	7
#include "rtd/infinitecloak.sp"		//	8
#include "rtd/criticals.sp"			//	9
#include "rtd/infiniteammo.sp"		//	10
#include "rtd/scarybullets.sp"		//	11
#include "rtd/spawnsentry.sp"		//	12
#include "rtd/homingprojectiles.sp"	//	13
#include "rtd/fullriflecharge.sp"	//	14
#include "rtd/explode.sp"			//	15
#include "rtd/snail.sp"				//	16
#include "rtd/frozen.sp"			//	17
#include "rtd/timebomb.sp"			//	18
#include "rtd/ignition.sp"			//	19
#include "rtd/lowhealth.sp"			//	20
#include "rtd/drugged.sp"			//	21
#include "rtd/blind.sp"				//	22
#include "rtd/striptomelee.sp"		//	23
#include "rtd/beacon.sp"			//	24
#include "rtd/forcedtaunt.sp"		//	25
#include "rtd/monochromia.sp"		//	26
#include "rtd/earthquake.sp"		//	27
#include "rtd/funnyfeeling.sp"		//	28
#include "rtd/badsauce.sp"			//	29
#include "rtd/spawndispenser.sp"	//	30
#include "rtd/infinitejump.sp"		//	31
#include "rtd/powerfulhits.sp"		//	32
#include "rtd/bighead.sp"			//	33
#include "rtd/tinymann.sp"			//	34
#include "rtd/firework.sp"			//	35
#include "rtd/deadlyvoice.sp"		//	36
#include "rtd/stronggravity.sp"		//	37
#include "rtd/eyeforaneye.sp"		//	38
#include "rtd/weakened.sp"			//	39
#include "rtd/necromash.sp"			//	40
#include "rtd/extraammo.sp"			//	41
#include "rtd/suffocation.sp"		//	42
#include "rtd/fasthands.sp"			//	43
#include "rtd/outline.sp"			//	44
#include "rtd/vital.sp"				//	45
#include "rtd/nogravity.sp"			//	46
#include "rtd/teamcriticals.sp"		//	47
#include "rtd/firetimebomb.sp"		//	48
#include "rtd/firebreath.sp"		//	49
#include "rtd/strongrecoil.sp"		//	50
#include "rtd/cursed.sp"			//	51
#include "rtd/extrathrowables.sp"	//	52
#include "rtd/powerplay.sp"			//	53
#include "rtd/explosivearrows.sp"	//	54
#include "rtd/inclineproblem.sp"	//	55